//! TOML configuration and CLI arguments
use crate::lang::Lang;
use crate::ui::color_preview::ColorPreview;
use clap::Parser;
use ratatui::style::Color;
use serde::{Deserialize, Serialize};
use std::{
    fs::{self, File},
    io::{self, Write},
    process,
};

#[derive(Deserialize, Serialize)]
#[serde(default)]
/// Root config file, targeting TOML.
pub struct Config {
    /// Test language
    pub lang: String,
    pub theme: ThemeCfg,
    /// How many words to test for
    pub word_count: u32,
    pub ui: UiCfg,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            lang: "english".to_string(),
            word_count: 50,
            theme: ThemeCfg::default(),
            ui: UiCfg::default(),
        }
    }
}

impl Config {
    /// Safely get the configuration from config directory, using defaults if it cannot be accessed.
    /// Then load CLI arguments and layer those options over the TOML configuration.
    /// Also creates a new default config if none exists at runtime.
    pub fn get() -> std::io::Result<Self> {
        let a = Args::get()?;
        let p = dirs::config_local_dir().unwrap().join("arstyper.toml");
        let s = fs::read_to_string(&p).unwrap_or_else(|e| {
            println!(
                "Error reading from {}: {e}\nAttempting to create default config...",
                p.display()
            );
            let c = format!(
                "# Default config generated by arstyper\n{}",
                toml::to_string(&Self::default()).unwrap()
            );

            match File::create(&p) {
                Ok(mut f) => {
                    f.write_all(c.as_bytes()).unwrap();
                    println!("Sucessfully wrote default config to {}", p.display());
                }
                Err(e) => {
                    println!("Error creating {}: {e}", p.display());
                    process::exit(0b1);
                }
            }

            "".to_string() // faster than returning c since its defaults anyways
        });

        let mut cfg: Self = toml::from_str(&s).unwrap_or_else(|e| {
            println!("{}: {e}", p.display());
            process::exit(0b1);
        });

        // layer args over cfg
        if let Some(l) = a.lang {
            cfg.lang = l;
        }
        if let Some(wc) = a.words {
            cfg.word_count = wc;
        }

        Ok(cfg)
    }
}

#[derive(Deserialize, Serialize)]
#[serde(default)]
/// Theme configuration, currently only supports named colors.
pub struct ThemeCfg {
    pub fg: Color,
    pub bg: Color,
    pub untyped_text: Color,
    pub typed_text: Color,
    pub incorrect_text: Color,
    pub accent: Color,
}

impl Default for ThemeCfg {
    fn default() -> Self {
        Self {
            fg: Color::White,
            bg: Color::Black,
            untyped_text: Color::White,
            typed_text: Color::DarkGray,
            incorrect_text: Color::Red,
            accent: Color::Magenta,
        }
    }
}

#[derive(Deserialize, Serialize)]
#[serde(default)]
/// Specific UI configuration to show or hide elements and change behaviours.
pub struct UiCfg {
    /// Show clock in bottom right of modeline
    pub show_clock: bool,
    /// 12 or 24 hour clock
    pub hour_24: bool,
}

impl Default for UiCfg {
    fn default() -> Self {
        Self {
            show_clock: true,
            hour_24: true,
        }
    }
}

/// arstyper - a minimal terminal-based typing test
#[derive(Parser)]
#[command(version, about, long_about = None)]
struct Args {
    /// List available languages
    #[arg(long)]
    list: bool,
    /// Select language
    #[arg(short, long)]
    lang: Option<String>,
    /// Specify test word count
    #[arg(short, long)]
    words: Option<u32>,
    /// Preview colors
    #[arg(long)]
    help_colors: bool,
    /// Print help about the config file
    #[arg(long)]
    help_config: bool,
}

impl Args {
    /// Get CLI arguments and follow potential pre-UI endpoints.
    fn get() -> std::io::Result<Self> {
        let a = Self::parse();

        if a.list {
            let mut h = io::stdout().lock();
            let _ = writeln!(h, "Available languages:");
            for l in Lang::list() {
                let _ = writeln!(h, "  {}", l.file_name().unwrap().to_str().unwrap());
            }
        } else if a.help_config {
            println!(
                r#"arstyper Configuration Information

The config file is automatically created on first run.
  - Re-generate it by deleting the config and re-running the program
  - Unpopulated fields will use sane defaults
  - CLI options take priority over config options

The config file is located at one of the following locations:
  Linux: ~/.config/arstyper.toml
  MacOS: $HOME/Library/Application Support/arstyper.toml
  Windows: %localappdata%/arstyper.toml

To preview supported Theme Colors:
  arstyper --help-colors"#
            );
        } else if a.help_colors {
            let c = ColorPreview::new();
            c.run()?;
        } else {
            return Ok(a);
        }

        process::exit(0b0);
    }
}
